apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpa
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    #apiVersion: extensions/v1beta1
    apiVersion: apps/v1
    kind: Deployment
    name: go-hpa
  targetCPUUtilizationPercentage: 15
